export const userAction = {
  FETCH_CURRENT_USER_DATA_REQUEST: "FETCH_CURRENT_USER_DATA_REQUEST",
  FETCH_CURRENT_USER_DATA_SUCCESS: "FETCH_CURRENT_USER_DATA_SUCCESS",
  FETCH_CURRENT_USER_DATA_FAILURE: "FETCH_CURRENT_USER_DATA_FAILURE",
};

export const commentsAction = {
  FETCH_COMMENTS_REQUEST: "FETCH_COMMENTS_REQUEST",
  FETCH_COMMENTS_SUCCESS: "FETCH_COMMENTS_SUCCESS",
  FETCH_COMMENTS_FAILURE: "FETCH_COMMENTS_FAILURE",
  ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAILURE: "ADD_COMMENT_FAILURE",
  DELETE_COMMENT_REQUEST: "DELETE_COMMENT_REQUEST",
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
  DELETE_COMMENT_FAILURE: "DELETE_COMMENT_FAILURE",
};

export const codeAction = {
  CONFIRMATION_CODE_REQUEST: "CONFIRMATION_CODE_REQUEST",
  CONFIRMATION_CODE_SUCCESS: "CONFIRMATION_CODE_SUCCESS",
  CONFIRMATION_CODE_FAILURE: "CONFIRMATION_CODE_FAILURE",
  START_TIMER: "START_TIMER",
  TIMER_TICKING: "TIMER_TICKING",
  STOP_TIMER: "STOP_TIMER",
};

export const favoritesAction = {
  FETCH_CURRENT_USER_FAVORITES_REQUEST: "FETCH_CURRENT_USER_FAVORITES_REQUEST",
  FETCH_CURRENT_USER_FAVORITES_SUCCESS: "FETCH_CURRENT_USER_FAVORITES_SUCCESS",
  FETCH_CURRENT_USER_FAVORITES_FAILURE: "FETCH_CURRENT_USER_FAVORITES_FAILURE",
};

export const chatsAction = {
  FETCH_CURRENT_USER_CHATS_REQUEST: "FETCH_CURRENT_USER_CHATS_REQUEST",
  FETCH_CURRENT_USER_CHATS_SUCCESS: "FETCH_CURRENT_USER_CHATS_SUCCESS",
  FETCH_CURRENT_USER_CHATS_FAILURE: "FETCH_CURRENT_USER_CHATS_FAILURE",
  FETCH_OTHER_USERS_REQUEST: "FETCH_OTHER_USERS_REQUEST",
  FETCH_OTHER_USERS_SUCCESS: "FETCH_OTHER_USERS_SUCCESS",
  FETCH_OTHER_USERS_FAILURE: "FETCH_OTHER_USERS_FAILURE",
};

export const wordsAction = {
  FETCH_FEED_REQUEST: "FETCH_FEED_REQUEST",
  FETCH_FEED_SUCCESS: "FETCH_FEED_SUCCESS",
  FETCH_FEED_FAILURE: "FETCH_FEED_FAILURE",
  FETCH_CURRENT_USER_WORDS_REQUEST: "FETCH_CURRENT_USER_WORDS_REQUEST",
  FETCH_CURRENT_USER_WORDS_SUCCESS: "FETCH_CURRENT_USER_WORDS_SUCCESS",
  FETCH_CURRENT_USER_WORDS_FAILURE: "FETCH_CURRENT_USER_WORDS_FAILURE",
  FETCH_DISCOVER_WORDS_REQUEST: "FETCH_DISCOVER_WORDS_REQUEST",
  FETCH_DISCOVER_WORDS_SUCCESS: "FETCH_DISCOVER_WORDS_SUCCESS",
  FETCH_DISCOVER_WORDS_FAILURE: "FETCH_DISCOVER_WORDS_FAILURE",
};

export const followingsAction = {
  FETCH_CURRENT_USER_FOLLOWINGS_REQUEST:
    "FETCH_CURRENT_USER_FOLLOWINGS_REQUEST",
  FETCH_CURRENT_USER_FOLLOWINGS_SUCCESS:
    "FETCH_CURRENT_USER_FOLLOWINGS_SUCCESS",
  FETCH_CURRENT_USER_FOLLOWINGS_FAILURE:
    "FETCH_CURRENT_USER_FOLLOWINGS_FAILURE",
};

export const followersAction = {
  FETCH_CURRENT_USER_FOLLOWERS_REQUEST: "FETCH_CURRENT_USER_FOLLOWERS_REQUEST",
  FETCH_CURRENT_USER_FOLLOWERS_SUCCESS: "FETCH_CURRENT_USER_FOLLOWERS_SUCCESS",
  FETCH_CURRENT_USER_FOLLOWERS_FAILURE: "FETCH_CURRENT_USER_FOLLOWERS_FAILURE",
};

export const notificationsAction = {
  FETCH_NOTIFICATIONS_REQUEST: "FETCH_CURRENT_USER_NOTIFICATIONS_REQUEST",
  FETCH_NOTIFICATIONS_SUCCESS: "FETCH_CURRENT_USER_NOTIFICATIONS_SUCCESS",
  FETCH_NOTIFICATIONS_FAILURE: "FETCH_CURRENT_USER_NOTIFICATIONS_FAILURE",
  NOTIFICATION_SETTING_STATUS: "NOTIFICATION_SETTING_STATUS",
};
