export const userAction = {
  FETCH_CURRENT_USER_DATA_REQUEST: "FETCH_CURRENT_USER_DATA_REQUEST",
  FETCH_CURRENT_USER_DATA_SUCCESS: "FETCH_CURRENT_USER_DATA_SUCCESS",
  FETCH_CURRENT_USER_DATA_FAILURE: "FETCH_CURRENT_USER_DATA_FAILURE",
};

export const codeAction = {
  CONFIRMATION_CODE_REQUEST: "CONFIRMATION_CODE_REQUEST",
  CONFIRMATION_CODE_SUCCESS: "CONFIRMATION_CODE_SUCCESS",
  CONFIRMATION_CODE_FAILURE: "CONFIRMATION_CODE_FAILURE",
  START_TIMER: "START_TIMER",
  TIMER_TICKING: "TIMER_TICKING",
  STOP_TIMER: "STOP_TIMER",
};

export const savesAction = {
  FETCH_CURRENT_USER_SAVES_REQUEST: "FETCH_CURRENT_USER_SAVES_REQUEST",
  FETCH_CURRENT_USER_SAVES_SUCCESS: "FETCH_CURRENT_USER_SAVES_SUCCESS",
  FETCH_CURRENT_USER_SAVES_FAILURE: "FETCH_CURRENT_USER_SAVES_FAILURE",
};

export const chatsAction = {
  FETCH_CURRENT_USER_CHATS_REQUEST: "FETCH_CURRENT_USER_CHATS_REQUEST",
  FETCH_CURRENT_USER_CHATS_SUCCESS: "FETCH_CURRENT_USER_CHATS_SUCCESS",
  FETCH_CURRENT_USER_CHATS_FAILURE: "FETCH_CURRENT_USER_CHATS_FAILURE",
  FETCH_OTHER_USERS_REQUEST: "FETCH_OTHER_USERS_REQUEST",
  FETCH_OTHER_USERS_SUCCESS: "FETCH_OTHER_USERS_SUCCESS",
  FETCH_OTHER_USERS_FAILURE: "FETCH_OTHER_USERS_FAILURE",
};

export const postsAction = {
  FETCH_FEED_REQUEST: "FETCH_FEED_REQUEST",
  FETCH_FEED_SUCCESS: "FETCH_FEED_SUCCESS",
  FETCH_FEED_FAILURE: "FETCH_FEED_FAILURE",
  FETCH_CURRENT_USER_POSTS_REQUEST: "FETCH_CURRENT_USER_POSTS_REQUEST",
  FETCH_CURRENT_USER_POSTS_SUCCESS: "FETCH_CURRENT_USER_POSTS_SUCCESS",
  FETCH_CURRENT_USER_POSTS_FAILURE: "FETCH_CURRENT_USER_POSTS_FAILURE",
  FETCH_DISCOVER_POSTS_REQUEST: "FETCH_DISCOVER_POSTS_REQUEST",
  FETCH_DISCOVER_POSTS_SUCCESS: "FETCH_DISCOVER_POSTS_SUCCESS",
  FETCH_DISCOVER_POSTS_FAILURE: "FETCH_DISCOVER_POSTS_FAILURE",
};

export const followingsAction = {
  FETCH_CURRENT_USER_FOLLOWINGS_REQUEST:
    "FETCH_CURRENT_USER_FOLLOWINGS_REQUEST",
  FETCH_CURRENT_USER_FOLLOWINGS_SUCCESS:
    "FETCH_CURRENT_USER_FOLLOWINGS_SUCCESS",
  FETCH_CURRENT_USER_FOLLOWINGS_FAILURE:
    "FETCH_CURRENT_USER_FOLLOWINGS_FAILURE",
};

export const followersAction = {
  FETCH_CURRENT_USER_FOLLOWERS_REQUEST: "FETCH_CURRENT_USER_FOLLOWERS_REQUEST",
  FETCH_CURRENT_USER_FOLLOWERS_SUCCESS: "FETCH_CURRENT_USER_FOLLOWERS_SUCCESS",
  FETCH_CURRENT_USER_FOLLOWERS_FAILURE: "FETCH_CURRENT_USER_FOLLOWERS_FAILURE",
};

export const notificationsAction = {
  FETCH_NOTIFICATIONS_REQUEST: "FETCH_CURRENT_USER_NOTIFICATIONS_REQUEST",
  FETCH_NOTIFICATIONS_SUCCESS: "FETCH_CURRENT_USER_NOTIFICATIONS_SUCCESS",
  FETCH_NOTIFICATIONS_FAILURE: "FETCH_CURRENT_USER_NOTIFICATIONS_FAILURE",
  NOTIFICATION_SETTING_STATUS: "NOTIFICATION_SETTING_STATUS",
};
