export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const LOADING = "LOADING";
export const CURRENT_USER_POSTS_UPDATE = "CURRENT_USER_POSTS_UPDATE";
export const POSTS_DISCOVER = "POSTS_DISCOVER";
export const USERS_STATE_CHANGE = "USERS_STATE_CHANGE";
export const USER_CHATS_STATE_CHANGE = "USER_CHATS_STATE_CHANGE";
export const CURRENT_USER_NOTIFICATIONS = "CURRENT_USER_NOTIFICATIONS";

export const USER_FOLLOWING_STATE_CHANGE = "USER_FOLLOWING_STATE_CHANGE";
